Enable publish to Azure Automation
dsccommunity/DscWorkshop pull request #130
Opened 2022-02-12 15:05 UTC by nyanhp

# Pull Request

## Pull Request (PR) description

Added stages to cloud pipeline and added steps to publish modules to Azure Automation DSC. Tested in my own Azure DevOps org

In order to publish and assign Guest Configuration Policies, more work is necessary and will follow later on. Most notably, creating the Guest Configuration Packages is only possible with PS7+.

To use this feature, the follow prerequisites are required:
- Service Connection to Azure Resource Manager has been created in Azure DevOps
- Storage Account exists, Service Connection has permissions
- Automation Account exists, Service Connection has permissions

### Added
- Publishing of modules and MOF to Azure Automation DSC
### Changed
- Updated module versions to be on par with CommonTasks 0.6.0

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2022-02-16 20:14 UTC, raandree requested changes
It works great, thanks!

One thing: I would like to add the new pipeline as a separate one, like `azure-pipelines with Deployment.yml`. The pipeline that you have created is the perfect template when using AA for DSC pull, but the build DSC Community's pipeline does not have access to an Azure Automation account.

@nyanhp, what are your thoughts on this?

2022-02-16 20:14 UTC, raandree commented on azure-pipelines.yml
> +        - task: AzurePowerShell@5
@nyanhp, what happens all the Azure resources are not defined. Will the task fail then or just being skipped?

2022-02-23 12:54 UTC, nyanhp commented on azure-pipelines.yml
> +        - task: AzurePowerShell@5
That makes sense, a separate pipeline would make sense

2022-02-24 18:07 UTC, raandree approved these changes

2022-02-24 18:07 UTC, merged